# Python CircleCI 2.0 configuration file
version: 2

"-": &test_steps
  steps:
    - checkout
    
    - restore_cache:  # ensure this step occurs *before* installing dependencies
        keys:
          - cache-{{ checksum "requirements.txt" }}
          - cache-
            
    - run:
        name: Installing pip requirements at top level
        command: |
          sudo pip install -r requirements.txt
            
    - run:
        name: Installing pip cloudvolume_requirements
        command: |
          sudo pip install -r ingestclient/plugins/requirements/cloudvolume_requirements.txt
            
    - save_cache:
        paths:
          - ~/.local
          - ~/.cache
        key: cache-{{ checksum "requirements.txt" }}

    ####  Run Tests
    - run:
        name: Setup Dummy AWS creds
        command: |
          mkdir ~/.aws
          echo -e "[default]\naws_access_key_id = foo\naws_secret_access_key = bar" > ~/.aws/credentials
          echo -e "[default]\nregion = us-east-1\noutput = json" > ~/.aws/config        

    - run:
        name: Running py3 tests ... python unit tests 
        command: |
          python -m unittest -v  

    - store_artifacts:
        path: /tmp
        destination: py3_tests


jobs:
  test_py3_8:
    <<: *test_steps
    docker:
      - image: circleci/python:3.8
  test_py3_7:
    <<: *test_steps
    docker:
      - image: circleci/python:3.7
  test_py3_6:
    <<: *test_steps
    docker:
      - image: circleci/python:3.6

workflows:
  version: 2
  test_all:
    jobs:
      - test_py3_8
      - test_py3_7
      - test_py3_6
